#!/bin/sh

config=()
read_config() {
  while read line; do
    config[${#config[*]}]=$line
  done < /etc/distcc/ssh-hosts
}

start_server() {
    array=(${config[$1]})
    host=${array[0]}
    port=${array[1]}
    path=${array[2]}
    log=${array[3]}
    tmp=${array[4]}
    DISTCC_SAVE_TEMPS=${DISTCC_SAVE_TEMPS:-0}
    echo "Starting distccd on $host:$port..."
    cmd="env DISTCC_SAVE_TEMPS=$DISTCC_SAVE_TEMPS TMPDIR=$tmp PATH=$path distccd --verbose --log-file=$log --daemon --no-detach --nice 10 --jobs 10 --port $port --allow 127.0.0.1 2>&1"
    ssh -q -f -L "$port:localhost:$port" "$host" "$cmd" 2>&1 > /dev/null
}

stop_server() {
    array=(${config[$1]})
    host=${array[0]}
    port=${array[1]}
    path=${array[2]}
    echo "Killing distccd on $host:$port..."
    cmd="killall distccd 2>&1 > /dev/null"
    ssh -q $host $cmd 2>&1 > /dev/null &
}

start() {
  read_config
  for i in ${!config[*]}; do
      start_server $i
  done
  echo "Cluster up and running!"
}

stop() {
  read_config
  for i in ${!config[*]}; do
      stop_server $i
  done
  echo "Cluster stopped"
}

restart() {
  read_config
  for i in ${!config[*]}; do
    stop_server $i
    start_server $i
  done
  echo "Cluster restarted"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
